AZURE_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=eccciseedashboardst;AccountKey=pjFcVLVSJkLXt4EOxKTta9xxndI95UuVoLcru0yWUC0aiJP4hWh+MY3G9SAVSz3i9z43X42rEabj+ASt2THCtg==;EndpointSuffix=core.windows.net"
